### PR TITLE
Retrigger to build for `aarch-64`

### PR DESCRIPTION
**Pull request by sumit0190**
No changes to the recipe

### CODE REVIEW

**Comment by skupr-anaconda** [comment]
Artifacts have been created for all platforms with new filename hashes. It's weird.

**Review by skupr-anaconda — APPROVED** [review]

**Comment by katietz** [comment]
please add the license-family key ... the other linter message are looking to me more like noise.

**Review by katietz — CHANGES_REQUESTED** [review]
plz add license_family, otherwise looks ok to me

**Comment by sumit0190** [comment]
Fixed all linter errors; only warnings remain.

**Review by varlackc — APPROVED** [review]
LGTM

**Pull request merged**
